version: "3.7"
services:
    jupyter:
      image: jupyter/datascience-notebook:latest
      container_name: jupy
      volumes:
        - ./volume/datasets:/home/jovyan/work/datasets
        - ./volume/notebooks:/home/jovyan/work/notebooks
      restart: always
      ports:
        - 10000:8888
      networks:
        - internal
    streamlit-app:
      image: anime-data-app:latest
      container_name: anime-app
      volumes:
        - ./volume/datasets:/app/datasets
        - ./volume/images:/app/images
      restart: always
      ports:
        - 10001:8501
      networks:
        - internal


networks:
  internal:
    name: jupyterNetwork
    driver: bridge


volumes:
  notebook_data: